version: "3.9"

services:
  postgres:
    container_name: postgresSD
    image: bitnami/postgresql:12.10.0
    restart: always
    ports:
      - '5432'
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_DATABASE=postgres
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=postgres
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME = kafka-internal.io
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes


    depends_on:
      - zookeeper

  server:
    container_name: server
    build: ./server
    ports:
      - "8005:8005"
    depends_on:
      - kafka
      - zookeeper

  serverventas:
    container_name: serverventas
    build: ./Tventas
    ports:
      - "8012:8012"
    depends_on:
      - kafka
      - zookeeper
      - server
  servercoord:
    container_name: servercoord
    build: ./Tcoordenadas
    ports:
      - "8010:8010"
    depends_on:
      - kafka
      - zookeeper
      - server

